kind: Service
apiVersion: v1
metadata:
  labels:
    Service: backend-feed
  name: backend-feed
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    Service: backend-feed