apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: frontend

    spec:
      containers:
      - image: zearaujo25/udacity-frontend 
        name: frontend
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      service: frontend