apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        service: frontend
        app: frontend
        api: external
    spec:
      containers:
      - image: andersonlando/udacity-frontend
        name: frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always

